# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- task: Npm@1
  displayName: Npm Install
  inputs:
    command: 'install'
    workingDir: 'HikePlannerFE'

- task: Npm@1
  displayName: Npm install latest angular globally
  inputs:
    command: 'custom'
    workingDir: 'HikePlannerFE'
    customCommand: 'install -g @angular/cli@latest'

- task: Npm@1
  displayName: Npm Run Build
  inputs:
    command: 'custom'
    workingDir: 'HikePlannerFE'
    customCommand: 'run build'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(7db5a42a-1fa9-40a3-8da3-4ed5fb8c49cb)'
    appType: 'webAppLinux'
    WebAppName: 'hikeplanner'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'